// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class GridEditor : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Arc R, [Om]"</summary>
        public string ArcR;

        /// <summary>"Arc X, [Om]"</summary>
        public string ArcX;

        /// <summary>"Branches"</summary>
        public string Branches;

        /// <summary>"Buses"</summary>
        public string Buses;

        /// <summary>"Equipment"</summary>
        public string Equips;

        /// <summary>"Mutual inductions"</summary>
        public string Mutuals;

        /// <summary>"Add new network: "</summary>
        public string NewGrid;

        /// <summary>"Name"</summary>
        public string NewGridPlaceholder;
    }
}
