// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages.Contact
{
    public partial class Contact : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Connect with us"</summary>
        public string ContactHeader;

        /// <summary>"Your E-mail"</summary>
        public string Email;

        /// <summary>"Enter E-mail"</summary>
        public string ErrorEmail;

        /// <summary>"Enter message"</summary>
        public string ErrorMessage;

        /// <summary>"Enter name"</summary>
        public string ErrorName;

        /// <summary>"Message"</summary>
        public string Message;

        /// <summary>"Your name"</summary>
        public string Name;

        /// <summary>"Send"</summary>
        public string Send;

        /// <summary>"Your message has been sent successfully!"</summary>
        public string Success;
    }
}
