// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Shared.Footer
{
    public partial class Footer : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Cookie Policy"</summary>
        public string Policy;

        /// <summary>"Terms of use"</summary>
        public string Terms;
    }
}
