// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class InputGrid : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Choose file(s)"</summary>
        public string Choose;

        /// <summary>"Clear"</summary>
        public string Clear;

        /// <summary>"Choose one or several json-format network file(s)"</summary>
        public string Info;

        /// <summary>"Upload"</summary>
        public string Upload;
    }
}
