// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Shared
{
    public partial class Header : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Add New Network"</summary>
        public string AddNewGrid;

        /// <summary>"Calculate everything and download to Excel file"</summary>
        public string Calculate_All;

        /// <summary>"Download file with network data"</summary>
        public string Download;

        /// <summary>"Switch language"</summary>
        public string Language;

        /// <summary>"Protocol"</summary>
        public string Log;

        /// <summary>"Add IEEE 14 test network"</summary>
        public string Test_IEEE14;

        /// <summary>"Upload a file with network data to the site"</summary>
        public string Upload;
    }
}
