// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class Index : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Welcome!"</summary>
        public string Index_Header;

        /// <summary>"На этом сайте Вы можете выполнить расчёт токов короткого замыкания в электрической сети на основе метода симметричных составляющих."</summary>
        public string Index_p1;

        /// <summary>"Мы не накладываем ограничения на цели выполнения расчётов: обучение, бизнес или исследования."</summary>
        public string Index_p2;

        /// <summary>"С чего начать работу можно посмотреть в нашем "</summary>
        public string Index_p3;

        /// <summary>"руководстве пользователя."</summary>
        public string Index_p3_1;

        /// <summary>"Для начала работы просто создайте свою "</summary>
        public string Index_p4_1;

        /// <summary>" новую сеть."</summary>
        public string Index_p4_2;

        /// <summary>"Switch language"</summary>
        public string Language;

        /// <summary>"Send"</summary>
        public string Send;
    }
}
