// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class Branches : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"angle"</summary>
        public string angle;

        /// <summary>"deg."</summary>
        public string deg;

        /// <summary>"EMF"</summary>
        public string EMF;

        /// <summary>"bus end"</summary>
        public string finBus;

        /// <summary>"Bus end name"</summary>
        public string finBusName;

        /// <summary>"Branch 1"</summary>
        public string firstBranch;

        /// <summary>"Grounding in zero sequence from the bus end"</summary>
        public string groundFinBus;

        /// <summary>"Grounding in zero sequence from the bus begin"</summary>
        public string groundStartBus;

        /// <summary>"kA"</summary>
        public string kA;

        /// <summary>"kV"</summary>
        public string kV;

        /// <summary>"MVA"</summary>
        public string MVA;

        /// <summary>"Mvar"</summary>
        public string Mvar;

        /// <summary>"MWt"</summary>
        public string MWt;

        /// <summary>"Om"</summary>
        public string ohm;

        /// <summary>"Branch 2"</summary>
        public string secondBranch;

        /// <summary>"S"</summary>
        public string Siemens;

        /// <summary>"bus begin"</summary>
        public string startBus;

        /// <summary>"Bus begin name"</summary>
        public string startBusName;

        /// <summary>"Transformer"</summary>
        public string trans;

        /// <summary>"Unom"</summary>
        public string Unom;
    }
}
