// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class Components : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Add element"</summary>
        public string Add;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"Delete row"</summary>
        public string Delete;

        /// <summary>"Copy row"</summary>
        public string Duplicate;

        /// <summary>"Edit"</summary>
        public string Edit;

        /// <summary>"View equipment"</summary>
        public string Equipment;

        /// <summary>"Clear filter"</summary>
        public string Filter_clear;

        /// <summary>"Save row"</summary>
        public string Save;
    }
}
