// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class Disclaimer : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Disclaimer"</summary>
        public string Header;

        /// <summary>"The license allows to use this resource without charge and with no commitment, when following conditions are fulfilled:"</summary>
        public string p1;

        /// <summary>"THE SOFTWARE AND CALCULATION RESULTS IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE"</summary>
        public string p2;

        /// <summary>"Nobody of authors, participants, sponsors, administrators, operators or ones, who is associated with the resource is responsible for inaccurate or invalid information found, and also if you operate with data from this or other websites."</summary>
        public string p3;

        /// <summary>"All marks, signs and names of trades, services and organizations, rights for design, author and related rights mentioned, used or cited, are owned by their legal possessors."</summary>
        public string p4;

        /// <summary>"If you are looking for calculation using verified software, please, contact organizations holding right to distribute the certificated software."</summary>
        public string p5;

        /// <summary>"Thank you for spending your time to read this information."</summary>
        public string p6;
    }
}
