// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class Cookie : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Cookie Policy"</summary>
        public string Header;

        /// <summary>"Obtaining and using personal information"</summary>
        public string Header2;

        /// <summary>"Cookies"</summary>
        public string Header3;

        /// <summary>"Users of this resource lime.engineer (hereinafter referred to as the Resource) give their consent for the Resource to use their IP address, cookie and geolocation data for marketing and static research from the moment the Resource starts using it. All collected data are impersonal, that is, they do not contain personal data: full name, passport data or any other data that allows you to identify a specific person. In case of disagreement with this condition, the User must leave the Resource.    "</summary>
        public string Par1;

        /// <summary>"The resource does not collect, store and process the personal data of Users: full name, passport data or any other data that allows you to identify a specific person. Also, the calculation model created by the user and the calculation results are not saved in any form on the server.    "</summary>
        public string Par2;

        /// <summary>"Cookies are small files that are used to collect statistics on website visits. This Resource uses cookies to identify your computer."</summary>
        public string Par3;

        /// <summary>"Our Resource uses analytical cookies to analyze the operation of the Resource in order to improve its functionality, including for the purpose of displaying advertising. The information obtained in this case can be transferred to third parties in an anonymous form to the server of web analytics services for storage and processing.    "</summary>
        public string Par4;

        /// <summary>"For the purpose of analyzing the operation of the Resource, cookies are used by the following web analytics service providers: Google Analytics and Yandex.Metrica (LLC &quot;Yandex &quot;)."</summary>
        public string Par5;
    }
}
