// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Shared
{
    public partial class Navs : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Advices"</summary>
        public string Navs_AdvBut;

        /// <summary>"Branches"</summary>
        public string Navs_BranchBut;

        /// <summary>"Calculation"</summary>
        public string Navs_CalcBut;

        /// <summary>"Contacts"</summary>
        public string Navs_ContactBut;

        /// <summary>"Equipment"</summary>
        public string Navs_EquipBut;

        /// <summary>"Home"</summary>
        public string Navs_HomeBut;

        /// <summary>"Mutual induction"</summary>
        public string Navs_MutBut;

        /// <summary>"Nodes"</summary>
        public string Navs_NodeBut;
    }
}
