// <auto-generated by="the Blazor I18n Text compiler" />
namespace TKZ.Client.I18nText.Pages
{
    public partial class Branches : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Active"</summary>
        public string ActiveFilter;

        /// <summary>"angle"</summary>
        public string angle;

        /// <summary>"Bus"</summary>
        public string Bus;

        /// <summary>"Cancel"</summary>
        public string Cancel;

        /// <summary>"deg."</summary>
        public string deg;

        /// <summary>"D"</summary>
        public string Duplicate;

        /// <summary>"Edit"</summary>
        public string Edit;

        /// <summary>"EMF"</summary>
        public string EMF;

        /// <summary>"Clear filter"</summary>
        public string Filter;

        /// <summary>"End bus"</summary>
        public string finBus;

        /// <summary>"Bus end name"</summary>
        public string finBusName;

        /// <summary>"Branch 1"</summary>
        public string firstBranch;

        /// <summary>"Ground"</summary>
        public string Ground;

        /// <summary>"Grounding in end bus"</summary>
        public string groundFinBus;

        /// <summary>"Grounding in start bus"</summary>
        public string groundStartBus;

        /// <summary>"Branches"</summary>
        public string Header;

        /// <summary>"IsActive"</summary>
        public string IsActive;

        /// <summary>"kA"</summary>
        public string kA;

        /// <summary>"kV"</summary>
        public string kV;

        /// <summary>"Mutual inductions"</summary>
        public string MutualHeader;

        /// <summary>"MVA"</summary>
        public string MVA;

        /// <summary>"Mvar"</summary>
        public string Mvar;

        /// <summary>"MWt"</summary>
        public string MWt;

        /// <summary>"Name"</summary>
        public string Name;

        /// <summary>"New"</summary>
        public string New;

        /// <summary>"Disabled"</summary>
        public string NotActiveFilter;

        /// <summary>"Parall. number"</summary>
        public string NumPar;

        /// <summary>"Om"</summary>
        public string ohm;

        /// <summary>"Save"</summary>
        public string Save;

        /// <summary>"Branch 2"</summary>
        public string secondBranch;

        /// <summary>"S"</summary>
        public string Siemens;

        /// <summary>"Start bus"</summary>
        public string startBus;

        /// <summary>"Bus begin name"</summary>
        public string startBusName;

        /// <summary>"Transformer"</summary>
        public string trans;

        /// <summary>"Unom"</summary>
        public string Unom;
    }
}
